###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:
  mariadb:
    image: mariadb:10.4
    container_name: rhelper-mariadb
    working_dir: /application
    volumes:
      - .:/application
    environment:
      - MYSQL_DATABASE=rhelper
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "8083:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: rhelper-phpmyadmin
    environment:
      - PMA_HOST=mariadb
      - PMA_USER=root
      - PMA_PASSWORD=root
      - PMA_DATABASE=rhelper
    restart: always
    ports:
      - "8082:80"
    volumes:
      - /sessions
    links:
      - mariadb

  webserver:
    image: nginx:alpine
    container_name: rhelper-webserver
    working_dir: /application
    volumes:
      - .:/application
      - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8081:80"
    links:
      - mariadb

  php-fpm:
    build: phpdocker/php-fpm
    container_name: rhelper-php-fpm
    working_dir: /application
    volumes:
      - .:/application
      - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini


